spring:
  application:
    name: starwars-testing
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS testdb\;SET SCHEMA testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
      globally_quoted_identifiers: false

server:
  port: 8080
